# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BgSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionY', models.FloatField(verbose_name='positionY_\u6846\u4e2d\u5fc3\u70b9\u5360\u6574\u4e2a\u5c4f\u5e55\u7684\u6bd4\u4f8b')),
                ('bottomBlkHeight', models.PositiveIntegerField(verbose_name='\u6846\u5185\u7684\u4e0b\u65b9\u7a7a\u767d\u7684\u9ad8')),
                ('imgurl', models.CharField(max_length=512, verbose_name='\u6846\u7684\u80cc\u666f\u56fe')),
            ],
            options={
                'verbose_name': '\u6846',
                'verbose_name_plural': '\u6846',
            },
        ),
        migrations.CreateModel(
            name='GameIconSwitchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wxAppId', models.CharField(choices=[(b'wx81319a080b7919e2', b'\xe6\x97\x85\xe8\xa1\x8c\xe5\xb0\x8f\xe8\xa5\xbf\xe7\x93\x9c'), (b'wx81df03575e1e351f', b'\xe7\xa5\x96\xe7\x8e\x9b\xe5\xbc\xb9\xe7\x90\x83'), (b'wxaa5c62c26ee49681', b'\xe7\x96\xaf\xe7\x8b\x82\xe6\x9e\xaa\xe6\x89\x8b'), (b'wxbfebdafc2fc60b54', b'\xe5\xaf\x8c\xe8\xb1\xaa\xe6\x96\x97\xe5\x9c\xb0\xe4\xb8\xbb'), (b'wxbb777fbea1e15f52', b'\xe6\x96\xb0\xe4\xbf\x84\xe7\xbd\x97\xe6\x96\xaf2048'), (b'wx799e9a8af511be76', b'\xe6\x9c\x80\xe5\xbc\xba\xe5\xb0\x8f\xe5\x85\x94\xe8\xb7\x91\xe9\x85\xb7\xe7\xbb\x8f\xe5\x85\xb8\xe7\x89\x88'), (b'wxb1d95fb6ebaf04eb', b'\xe5\x8d\x81\xe5\xad\x97\xe6\xb6\x88\xe6\xb6\x88\xe6\xb6\x88'), (b'wx9f3847ace08e2ef0', b'2048\xe5\x90\x88\xe5\xb9\xb6'), (b'wx57f49f44206958e6', b'\xe6\xac\xa2\xe4\xb9\x90\xe9\x92\x93\xe9\xb1\xbc\xe5\xa4\xa7\xe5\xb8\x88'), (b'wxf1e6cc8e12d25d1f', b'2048\xe5\x8d\xa1\xe7\x89\x8c\xe6\x8e\xa5\xe9\xbe\x99'), (b'wx6a9fc3d2c62410d8', b'\xe5\xa4\xa9\xe5\xa4\xa9\xe7\x8b\x99\xe5\x87\xbb'), (b'wx824d94ce511885ad', b'\xe5\x8f\x8c\xe6\x9e\xaa\xe7\x8e\x8b\xe8\x80\x85'), (b'wxb082d51f37021fac', b'\xe6\x95\xb0\xe5\xad\x97\xe6\xb6\x88\xe6\xb6\x88\xe4\xb9\x902'), (b'wxe28531ea9f8164dc', b'\xe6\xac\xa2\xe4\xb9\x90\xe6\x8c\x96\xe7\x9f\xbf\xe5\xa4\xa7\xe5\xb8\x88'), (b'wx3e051a032d2386e9', b'\xe7\xa2\xb0\xe6\x92\x9e\xe7\x90\x83\xe7\x90\x83'), (b'wxc1b648fc2fbc7ce8', b'\xe5\x8d\x95\xe6\x9c\xba\xe6\x96\x97\xe5\x9c\xb0\xe4\xb8\xbb'), (b'wx160e205dd45116c4', b'\xe7\x90\x83\xe7\x90\x83\xe5\xa4\xa7\xe6\xb6\x88\xe9\x99\xa4'), (b'wxde9361a6865997fc', b'3D\xe7\x90\x83\xe7\x90\x83\xe6\x89\x93\xe7\xa0\x96\xe5\x9d\x97'), (b'wxd7062438a8b82506', b'\xe7\x96\xaf\xe7\x8b\x82\xe6\x96\xa7\xe5\xa4\xb4'), (b'wx352edabae2ef7a26', b'\xe5\x90\x88\xe5\x88\xb08'), (b'wxca71cd422b7fa67c', b'\xe5\x90\x88\xe5\xb9\xb6\xe4\xb8\x89\xe5\x9b\xbd'), (b'wxa3855d93c407a5b6', b'\xe6\xac\xa2\xe4\xb9\x90\xe5\x88\x87\xe6\xb0\xb4\xe6\x9e\x9c\xe5\xa4\xa7\xe5\xb8\x88'), (b'wx950f5176e1d4ea9c', b'\xe6\xac\xa2\xe4\xb9\x90\xe5\xb0\x84\xe5\x87\xbb\xe5\xa4\xa7\xe5\xb8\x88'), (b'wx234bfd171f00b4fc', b'3D\xe6\xb6\x82\xe8\x89\xb2\xe8\xbf\xb7\xe5\xae\xab'), (b'wx7a2ecd52309f2466', b'\xe4\xbf\x84\xe7\xbd\x97\xe6\x96\xaf\xe6\x96\xb9\xe5\x9d\x97\xe6\xb6\x88\xe9\x99\xa4\xe4\xbc\xa0\xe5\xa5\x87'), (b'wx2ff277bf28f5b970', b'\xe9\xa3\x9e\xe5\x88\x80\xe5\xaf\xb9\xe6\x88\x98'), (b'wx1668490543c6bae9', b'\xe5\xa4\xa9\xe5\xa4\xa9\xe6\xb8\xb8\xe4\xb9\x90\xe5\x9c\xba'), (b'wx785e80cff6120de5', b'\xe9\x80\x94\xe6\xb8\xb8\xe6\x96\x97\xe5\x9c\xb0\xe4\xb8\xbb'), (b'wx79ade44c39cefc7f', b'\xe4\xbc\xa0\xe5\xa5\x87\xe6\x9d\xa5\xe4\xba\x86'), (b'wxe11c116fc919cca1', b'\xe4\xb8\x96\xe7\x95\x8c\xe4\xba\x89\xe9\x9c\xb8'), (b'wx45e02fc734c7b568', b'\xe4\xbf\x84\xe7\xbd\x97\xe6\x96\xaf\xe6\x96\xb9\xe5\x9d\x97\xe6\x8b\xbc\xe5\x9b\xbe'), (b'wxe46bd15fcbb4f829', b'\xe6\xac\xa2\xe4\xb9\x90\xe9\x80\x94\xe6\xb8\xb8\xe9\xba\xbb\xe5\xb0\x86'), (b'wx30efe34580243475', b'\xe9\x80\x94\xe6\xb8\xb8\xe4\xbc\x91\xe9\x97\xb2\xe6\x8d\x95\xe9\xb1\xbc'), (b'wxa9b801abd43333d9', b'\xe9\x80\x94\xe6\xb8\xb8\xe5\x9b\x9b\xe5\xb7\x9d\xe9\xba\xbb\xe5\xb0\x86'), (b'wx4806f332084cae85', b'\xe9\x80\x94\xe6\xb8\xb8\xe6\x8d\x95\xe9\xb1\xbc'), (b'wx7cc3368d8ea0ed18', b'3D\xe6\x88\x98\xe8\xad\xa6'), (b'wx85e9ff1a243bd54c', b'\xe8\xa5\xbf\xe9\x83\xa8\xe5\xb0\x84\xe6\x9d\x80'), (b'wx656cf75188e899bf', b'\xe7\x8e\x8b\xe5\x9b\xbd\xe6\x97\xa0\xe6\x95\x8c'), (b'wxe20385ecec37a61d', b'\xe6\x90\xad\xe6\x9c\xa8\xe6\x9d\xbf'), (b'wxd9dac6412c7dab7b', b'\xe6\xac\xa2\xe4\xb9\x90\xe5\x8a\xa01'), (b'wx9bb2c795e0a6cc26', b'\xe6\x95\xb0\xe5\xad\x97\xe4\xb8\x89\xe6\xb6\x88'), (b'wxb92d4d650d51eda8', b'2048\xe5\x85\xad\xe8\xa7\x92\xe6\xb6\x88\xe9\x99\xa4'), (b'wx9b028af0bedc1ea7', b'\xe6\x98\x9f\xe6\x98\x9f\xe8\x90\x8c\xe7\xbf\xbb\xe5\xa4\xa9'), (b'wx38ba6e1a02228283', b'\xe7\x8e\xa9\xe7\x88\x862048'), (b'wx760b441f8a68d7c6', b'\xe6\x9e\xaa\xe6\x89\x8b\xe6\x9d\xa5\xe4\xba\x86'), (b'wx148b43768fd2f0c8', b'\xe7\x90\x83\xe7\x90\x83\xe9\xa3\x9e\xe8\xbd\xa6'), (b'wx30b605819c95270b', b'\xe6\x88\x98\xe7\xa5\x9e\xe5\xbd\x95'), (b'wx7243aa518129131d', b'\xe6\xb2\x99\xe5\x9f\x8e\xe6\x88\x98\xe7\xa5\x9e'), (b'wx6ae9fecf13de0423', b'\xe5\xb7\xa6\xe5\x8f\xb3\xe5\x86\xb2\xe9\xb8\xad'), (b'wxd82849dc23eb4ac0', b'\xe6\x8c\xaa\xe8\xbd\xa6\xe5\xa4\xa7\xe5\xb8\x88'), (b'wxdb030d1934b15d67', b'\xe6\x95\xb0\xe5\xad\x97\xe6\xb3\xa1\xe6\xb3\xa1'), (b'wx4b05395b61fd2aaf', b'\xe9\x80\x94\xe6\xb8\xb8\xe6\xb8\xb8\xe6\x88\x8f')], max_length=20, verbose_name='wxAppId')),
                ('weight', models.PositiveIntegerField(verbose_name='\u6743\u91cd')),
                ('scale', models.FloatField(verbose_name='\u7f29\u653e\u6bd4\u4f8b')),
                ('imgLink', models.CharField(max_length=512, verbose_name='ICON')),
                ('openType', models.BooleanField(default=1, verbose_name='\u6253\u5f00\u65b9\u5f0f')),
                ('clickHide', models.BooleanField(verbose_name='\u662f\u5426\u9690\u85cf')),
                ('topath', models.CharField(max_length=512, verbose_name='topath')),
                ('bi_iconId', models.CharField(max_length=10, verbose_name='bI_IconId')),
                ('bi_landing_page', models.CharField(max_length=512, verbose_name='bI_\u843d\u5730\u9875')),
                ('bi_landing_page_id', models.CharField(max_length=10, verbose_name='bI_\u843d\u5730\u9875Id')),
                ('bi_educe_game', models.CharField(max_length=10, verbose_name='bI_\u6e20\u9053\u6807\u8bc6')),
            ],
            options={
                'verbose_name': '\u5bfc\u51fa\u6e38\u620f',
                'verbose_name_plural': '\u5bfc\u51fa\u6e38\u620f',
            },
        ),
        migrations.CreateModel(
            name='GameSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='\u8f93\u5165\u6570\u5b57', verbose_name='\u5e8f\u53f7')),
                ('text', models.CharField(max_length=512, verbose_name='text')),
                ('type', models.BooleanField(default=0, verbose_name='\u52a8\u56feicon')),
                ('imgLink', models.CharField(max_length=512, verbose_name='ICON')),
                ('openType', models.BooleanField(default=1, verbose_name='\u6253\u5f00\u65b9\u5f0f')),
                ('openUrl', models.CharField(choices=[(b'wx81319a080b7919e2', b'\xe6\x97\x85\xe8\xa1\x8c\xe5\xb0\x8f\xe8\xa5\xbf\xe7\x93\x9c'), (b'wx81df03575e1e351f', b'\xe7\xa5\x96\xe7\x8e\x9b\xe5\xbc\xb9\xe7\x90\x83'), (b'wxaa5c62c26ee49681', b'\xe7\x96\xaf\xe7\x8b\x82\xe6\x9e\xaa\xe6\x89\x8b'), (b'wxbfebdafc2fc60b54', b'\xe5\xaf\x8c\xe8\xb1\xaa\xe6\x96\x97\xe5\x9c\xb0\xe4\xb8\xbb'), (b'wxbb777fbea1e15f52', b'\xe6\x96\xb0\xe4\xbf\x84\xe7\xbd\x97\xe6\x96\xaf2048'), (b'wx799e9a8af511be76', b'\xe6\x9c\x80\xe5\xbc\xba\xe5\xb0\x8f\xe5\x85\x94\xe8\xb7\x91\xe9\x85\xb7\xe7\xbb\x8f\xe5\x85\xb8\xe7\x89\x88'), (b'wxb1d95fb6ebaf04eb', b'\xe5\x8d\x81\xe5\xad\x97\xe6\xb6\x88\xe6\xb6\x88\xe6\xb6\x88'), (b'wx9f3847ace08e2ef0', b'2048\xe5\x90\x88\xe5\xb9\xb6'), (b'wx57f49f44206958e6', b'\xe6\xac\xa2\xe4\xb9\x90\xe9\x92\x93\xe9\xb1\xbc\xe5\xa4\xa7\xe5\xb8\x88'), (b'wxf1e6cc8e12d25d1f', b'2048\xe5\x8d\xa1\xe7\x89\x8c\xe6\x8e\xa5\xe9\xbe\x99'), (b'wx6a9fc3d2c62410d8', b'\xe5\xa4\xa9\xe5\xa4\xa9\xe7\x8b\x99\xe5\x87\xbb'), (b'wx824d94ce511885ad', b'\xe5\x8f\x8c\xe6\x9e\xaa\xe7\x8e\x8b\xe8\x80\x85'), (b'wxb082d51f37021fac', b'\xe6\x95\xb0\xe5\xad\x97\xe6\xb6\x88\xe6\xb6\x88\xe4\xb9\x902'), (b'wxe28531ea9f8164dc', b'\xe6\xac\xa2\xe4\xb9\x90\xe6\x8c\x96\xe7\x9f\xbf\xe5\xa4\xa7\xe5\xb8\x88'), (b'wx3e051a032d2386e9', b'\xe7\xa2\xb0\xe6\x92\x9e\xe7\x90\x83\xe7\x90\x83'), (b'wxc1b648fc2fbc7ce8', b'\xe5\x8d\x95\xe6\x9c\xba\xe6\x96\x97\xe5\x9c\xb0\xe4\xb8\xbb'), (b'wx160e205dd45116c4', b'\xe7\x90\x83\xe7\x90\x83\xe5\xa4\xa7\xe6\xb6\x88\xe9\x99\xa4'), (b'wxde9361a6865997fc', b'3D\xe7\x90\x83\xe7\x90\x83\xe6\x89\x93\xe7\xa0\x96\xe5\x9d\x97'), (b'wxd7062438a8b82506', b'\xe7\x96\xaf\xe7\x8b\x82\xe6\x96\xa7\xe5\xa4\xb4'), (b'wx352edabae2ef7a26', b'\xe5\x90\x88\xe5\x88\xb08'), (b'wxca71cd422b7fa67c', b'\xe5\x90\x88\xe5\xb9\xb6\xe4\xb8\x89\xe5\x9b\xbd'), (b'wxa3855d93c407a5b6', b'\xe6\xac\xa2\xe4\xb9\x90\xe5\x88\x87\xe6\xb0\xb4\xe6\x9e\x9c\xe5\xa4\xa7\xe5\xb8\x88'), (b'wx950f5176e1d4ea9c', b'\xe6\xac\xa2\xe4\xb9\x90\xe5\xb0\x84\xe5\x87\xbb\xe5\xa4\xa7\xe5\xb8\x88'), (b'wx234bfd171f00b4fc', b'3D\xe6\xb6\x82\xe8\x89\xb2\xe8\xbf\xb7\xe5\xae\xab'), (b'wx7a2ecd52309f2466', b'\xe4\xbf\x84\xe7\xbd\x97\xe6\x96\xaf\xe6\x96\xb9\xe5\x9d\x97\xe6\xb6\x88\xe9\x99\xa4\xe4\xbc\xa0\xe5\xa5\x87'), (b'wx2ff277bf28f5b970', b'\xe9\xa3\x9e\xe5\x88\x80\xe5\xaf\xb9\xe6\x88\x98'), (b'wx1668490543c6bae9', b'\xe5\xa4\xa9\xe5\xa4\xa9\xe6\xb8\xb8\xe4\xb9\x90\xe5\x9c\xba'), (b'wx785e80cff6120de5', b'\xe9\x80\x94\xe6\xb8\xb8\xe6\x96\x97\xe5\x9c\xb0\xe4\xb8\xbb'), (b'wx79ade44c39cefc7f', b'\xe4\xbc\xa0\xe5\xa5\x87\xe6\x9d\xa5\xe4\xba\x86'), (b'wxe11c116fc919cca1', b'\xe4\xb8\x96\xe7\x95\x8c\xe4\xba\x89\xe9\x9c\xb8'), (b'wx45e02fc734c7b568', b'\xe4\xbf\x84\xe7\xbd\x97\xe6\x96\xaf\xe6\x96\xb9\xe5\x9d\x97\xe6\x8b\xbc\xe5\x9b\xbe'), (b'wxe46bd15fcbb4f829', b'\xe6\xac\xa2\xe4\xb9\x90\xe9\x80\x94\xe6\xb8\xb8\xe9\xba\xbb\xe5\xb0\x86'), (b'wx30efe34580243475', b'\xe9\x80\x94\xe6\xb8\xb8\xe4\xbc\x91\xe9\x97\xb2\xe6\x8d\x95\xe9\xb1\xbc'), (b'wxa9b801abd43333d9', b'\xe9\x80\x94\xe6\xb8\xb8\xe5\x9b\x9b\xe5\xb7\x9d\xe9\xba\xbb\xe5\xb0\x86'), (b'wx4806f332084cae85', b'\xe9\x80\x94\xe6\xb8\xb8\xe6\x8d\x95\xe9\xb1\xbc'), (b'wx7cc3368d8ea0ed18', b'3D\xe6\x88\x98\xe8\xad\xa6'), (b'wx85e9ff1a243bd54c', b'\xe8\xa5\xbf\xe9\x83\xa8\xe5\xb0\x84\xe6\x9d\x80'), (b'wx656cf75188e899bf', b'\xe7\x8e\x8b\xe5\x9b\xbd\xe6\x97\xa0\xe6\x95\x8c'), (b'wxe20385ecec37a61d', b'\xe6\x90\xad\xe6\x9c\xa8\xe6\x9d\xbf'), (b'wxd9dac6412c7dab7b', b'\xe6\xac\xa2\xe4\xb9\x90\xe5\x8a\xa01'), (b'wx9bb2c795e0a6cc26', b'\xe6\x95\xb0\xe5\xad\x97\xe4\xb8\x89\xe6\xb6\x88'), (b'wxb92d4d650d51eda8', b'2048\xe5\x85\xad\xe8\xa7\x92\xe6\xb6\x88\xe9\x99\xa4'), (b'wx9b028af0bedc1ea7', b'\xe6\x98\x9f\xe6\x98\x9f\xe8\x90\x8c\xe7\xbf\xbb\xe5\xa4\xa9'), (b'wx38ba6e1a02228283', b'\xe7\x8e\xa9\xe7\x88\x862048'), (b'wx760b441f8a68d7c6', b'\xe6\x9e\xaa\xe6\x89\x8b\xe6\x9d\xa5\xe4\xba\x86'), (b'wx148b43768fd2f0c8', b'\xe7\x90\x83\xe7\x90\x83\xe9\xa3\x9e\xe8\xbd\xa6'), (b'wx30b605819c95270b', b'\xe6\x88\x98\xe7\xa5\x9e\xe5\xbd\x95'), (b'wx7243aa518129131d', b'\xe6\xb2\x99\xe5\x9f\x8e\xe6\x88\x98\xe7\xa5\x9e'), (b'wx6ae9fecf13de0423', b'\xe5\xb7\xa6\xe5\x8f\xb3\xe5\x86\xb2\xe9\xb8\xad'), (b'wxd82849dc23eb4ac0', b'\xe6\x8c\xaa\xe8\xbd\xa6\xe5\xa4\xa7\xe5\xb8\x88'), (b'wxdb030d1934b15d67', b'\xe6\x95\xb0\xe5\xad\x97\xe6\xb3\xa1\xe6\xb3\xa1'), (b'wx4b05395b61fd2aaf', b'\xe9\x80\x94\xe6\xb8\xb8\xe6\xb8\xb8\xe6\x88\x8f')], max_length=20, verbose_name='wxAppId')),
                ('isredon', models.BooleanField(default=1, verbose_name='\u663e\u793a\u7ea2\u70b9')),
                ('topath', models.CharField(max_length=512, verbose_name='topath')),
                ('bi_iconId', models.CharField(max_length=10, verbose_name='bI_IconId')),
                ('bi_landing_page', models.CharField(max_length=512, verbose_name='bI_\u843d\u5730\u9875')),
                ('bi_landing_page_id', models.CharField(max_length=10, verbose_name='bI_\u843d\u5730\u9875Id')),
                ('bi_educe_game', models.CharField(max_length=10, verbose_name='bI_\u6e20\u9053\u6807\u8bc6')),
            ],
            options={
                'verbose_name': '\u5bfc\u51fa\u6e38\u620f',
                'verbose_name_plural': '\u5bfc\u51fa\u6e38\u620f',
            },
        ),
        migrations.CreateModel(
            name='GameStripModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='\u8f93\u5165\u6570\u5b57', verbose_name='\u5e8f\u53f7')),
                ('wxAppId', models.CharField(choices=[(b'wx81319a080b7919e2', b'\xe6\x97\x85\xe8\xa1\x8c\xe5\xb0\x8f\xe8\xa5\xbf\xe7\x93\x9c'), (b'wx81df03575e1e351f', b'\xe7\xa5\x96\xe7\x8e\x9b\xe5\xbc\xb9\xe7\x90\x83'), (b'wxaa5c62c26ee49681', b'\xe7\x96\xaf\xe7\x8b\x82\xe6\x9e\xaa\xe6\x89\x8b'), (b'wxbfebdafc2fc60b54', b'\xe5\xaf\x8c\xe8\xb1\xaa\xe6\x96\x97\xe5\x9c\xb0\xe4\xb8\xbb'), (b'wxbb777fbea1e15f52', b'\xe6\x96\xb0\xe4\xbf\x84\xe7\xbd\x97\xe6\x96\xaf2048'), (b'wx799e9a8af511be76', b'\xe6\x9c\x80\xe5\xbc\xba\xe5\xb0\x8f\xe5\x85\x94\xe8\xb7\x91\xe9\x85\xb7\xe7\xbb\x8f\xe5\x85\xb8\xe7\x89\x88'), (b'wxb1d95fb6ebaf04eb', b'\xe5\x8d\x81\xe5\xad\x97\xe6\xb6\x88\xe6\xb6\x88\xe6\xb6\x88'), (b'wx9f3847ace08e2ef0', b'2048\xe5\x90\x88\xe5\xb9\xb6'), (b'wx57f49f44206958e6', b'\xe6\xac\xa2\xe4\xb9\x90\xe9\x92\x93\xe9\xb1\xbc\xe5\xa4\xa7\xe5\xb8\x88'), (b'wxf1e6cc8e12d25d1f', b'2048\xe5\x8d\xa1\xe7\x89\x8c\xe6\x8e\xa5\xe9\xbe\x99'), (b'wx6a9fc3d2c62410d8', b'\xe5\xa4\xa9\xe5\xa4\xa9\xe7\x8b\x99\xe5\x87\xbb'), (b'wx824d94ce511885ad', b'\xe5\x8f\x8c\xe6\x9e\xaa\xe7\x8e\x8b\xe8\x80\x85'), (b'wxb082d51f37021fac', b'\xe6\x95\xb0\xe5\xad\x97\xe6\xb6\x88\xe6\xb6\x88\xe4\xb9\x902'), (b'wxe28531ea9f8164dc', b'\xe6\xac\xa2\xe4\xb9\x90\xe6\x8c\x96\xe7\x9f\xbf\xe5\xa4\xa7\xe5\xb8\x88'), (b'wx3e051a032d2386e9', b'\xe7\xa2\xb0\xe6\x92\x9e\xe7\x90\x83\xe7\x90\x83'), (b'wxc1b648fc2fbc7ce8', b'\xe5\x8d\x95\xe6\x9c\xba\xe6\x96\x97\xe5\x9c\xb0\xe4\xb8\xbb'), (b'wx160e205dd45116c4', b'\xe7\x90\x83\xe7\x90\x83\xe5\xa4\xa7\xe6\xb6\x88\xe9\x99\xa4'), (b'wxde9361a6865997fc', b'3D\xe7\x90\x83\xe7\x90\x83\xe6\x89\x93\xe7\xa0\x96\xe5\x9d\x97'), (b'wxd7062438a8b82506', b'\xe7\x96\xaf\xe7\x8b\x82\xe6\x96\xa7\xe5\xa4\xb4'), (b'wx352edabae2ef7a26', b'\xe5\x90\x88\xe5\x88\xb08'), (b'wxca71cd422b7fa67c', b'\xe5\x90\x88\xe5\xb9\xb6\xe4\xb8\x89\xe5\x9b\xbd'), (b'wxa3855d93c407a5b6', b'\xe6\xac\xa2\xe4\xb9\x90\xe5\x88\x87\xe6\xb0\xb4\xe6\x9e\x9c\xe5\xa4\xa7\xe5\xb8\x88'), (b'wx950f5176e1d4ea9c', b'\xe6\xac\xa2\xe4\xb9\x90\xe5\xb0\x84\xe5\x87\xbb\xe5\xa4\xa7\xe5\xb8\x88'), (b'wx234bfd171f00b4fc', b'3D\xe6\xb6\x82\xe8\x89\xb2\xe8\xbf\xb7\xe5\xae\xab'), (b'wx7a2ecd52309f2466', b'\xe4\xbf\x84\xe7\xbd\x97\xe6\x96\xaf\xe6\x96\xb9\xe5\x9d\x97\xe6\xb6\x88\xe9\x99\xa4\xe4\xbc\xa0\xe5\xa5\x87'), (b'wx2ff277bf28f5b970', b'\xe9\xa3\x9e\xe5\x88\x80\xe5\xaf\xb9\xe6\x88\x98'), (b'wx1668490543c6bae9', b'\xe5\xa4\xa9\xe5\xa4\xa9\xe6\xb8\xb8\xe4\xb9\x90\xe5\x9c\xba'), (b'wx785e80cff6120de5', b'\xe9\x80\x94\xe6\xb8\xb8\xe6\x96\x97\xe5\x9c\xb0\xe4\xb8\xbb'), (b'wx79ade44c39cefc7f', b'\xe4\xbc\xa0\xe5\xa5\x87\xe6\x9d\xa5\xe4\xba\x86'), (b'wxe11c116fc919cca1', b'\xe4\xb8\x96\xe7\x95\x8c\xe4\xba\x89\xe9\x9c\xb8'), (b'wx45e02fc734c7b568', b'\xe4\xbf\x84\xe7\xbd\x97\xe6\x96\xaf\xe6\x96\xb9\xe5\x9d\x97\xe6\x8b\xbc\xe5\x9b\xbe'), (b'wxe46bd15fcbb4f829', b'\xe6\xac\xa2\xe4\xb9\x90\xe9\x80\x94\xe6\xb8\xb8\xe9\xba\xbb\xe5\xb0\x86'), (b'wx30efe34580243475', b'\xe9\x80\x94\xe6\xb8\xb8\xe4\xbc\x91\xe9\x97\xb2\xe6\x8d\x95\xe9\xb1\xbc'), (b'wxa9b801abd43333d9', b'\xe9\x80\x94\xe6\xb8\xb8\xe5\x9b\x9b\xe5\xb7\x9d\xe9\xba\xbb\xe5\xb0\x86'), (b'wx4806f332084cae85', b'\xe9\x80\x94\xe6\xb8\xb8\xe6\x8d\x95\xe9\xb1\xbc'), (b'wx7cc3368d8ea0ed18', b'3D\xe6\x88\x98\xe8\xad\xa6'), (b'wx85e9ff1a243bd54c', b'\xe8\xa5\xbf\xe9\x83\xa8\xe5\xb0\x84\xe6\x9d\x80'), (b'wx656cf75188e899bf', b'\xe7\x8e\x8b\xe5\x9b\xbd\xe6\x97\xa0\xe6\x95\x8c'), (b'wxe20385ecec37a61d', b'\xe6\x90\xad\xe6\x9c\xa8\xe6\x9d\xbf'), (b'wxd9dac6412c7dab7b', b'\xe6\xac\xa2\xe4\xb9\x90\xe5\x8a\xa01'), (b'wx9bb2c795e0a6cc26', b'\xe6\x95\xb0\xe5\xad\x97\xe4\xb8\x89\xe6\xb6\x88'), (b'wxb92d4d650d51eda8', b'2048\xe5\x85\xad\xe8\xa7\x92\xe6\xb6\x88\xe9\x99\xa4'), (b'wx9b028af0bedc1ea7', b'\xe6\x98\x9f\xe6\x98\x9f\xe8\x90\x8c\xe7\xbf\xbb\xe5\xa4\xa9'), (b'wx38ba6e1a02228283', b'\xe7\x8e\xa9\xe7\x88\x862048'), (b'wx760b441f8a68d7c6', b'\xe6\x9e\xaa\xe6\x89\x8b\xe6\x9d\xa5\xe4\xba\x86'), (b'wx148b43768fd2f0c8', b'\xe7\x90\x83\xe7\x90\x83\xe9\xa3\x9e\xe8\xbd\xa6'), (b'wx30b605819c95270b', b'\xe6\x88\x98\xe7\xa5\x9e\xe5\xbd\x95'), (b'wx7243aa518129131d', b'\xe6\xb2\x99\xe5\x9f\x8e\xe6\x88\x98\xe7\xa5\x9e'), (b'wx6ae9fecf13de0423', b'\xe5\xb7\xa6\xe5\x8f\xb3\xe5\x86\xb2\xe9\xb8\xad'), (b'wxd82849dc23eb4ac0', b'\xe6\x8c\xaa\xe8\xbd\xa6\xe5\xa4\xa7\xe5\xb8\x88'), (b'wxdb030d1934b15d67', b'\xe6\x95\xb0\xe5\xad\x97\xe6\xb3\xa1\xe6\xb3\xa1'), (b'wx4b05395b61fd2aaf', b'\xe9\x80\x94\xe6\xb8\xb8\xe6\xb8\xb8\xe6\x88\x8f')], max_length=20, verbose_name='wxAppId')),
                ('imgLink', models.CharField(max_length=512, verbose_name='ICON')),
                ('topath', models.CharField(max_length=512, verbose_name='topath')),
                ('isClickHide', models.BooleanField(verbose_name='\u662f\u5426\u9690\u85cf')),
                ('bi_iconId', models.CharField(max_length=10, verbose_name='bI_IconId')),
                ('bi_landing_page', models.CharField(max_length=512, verbose_name='bI_\u843d\u5730\u9875')),
                ('bi_landing_page_id', models.CharField(max_length=10, verbose_name='bI_\u843d\u5730\u9875Id')),
                ('bi_educe_game', models.CharField(max_length=10, verbose_name='bI_\u6e20\u9053\u6807\u8bc6')),
            ],
            options={
                'verbose_name': '\u5bfc\u51fa\u6e38\u620f',
                'verbose_name_plural': '\u5bfc\u51fa\u6e38\u620f',
            },
        ),
        migrations.CreateModel(
            name='GridSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconsWidth', models.IntegerField(verbose_name='iconsWidth')),
                ('iconsHeight', models.IntegerField(verbose_name='iconsHeight')),
                ('spacingX', models.IntegerField(verbose_name='spacingX')),
                ('spacingY', models.IntegerField(verbose_name='spacingY')),
                ('paddingLeft', models.IntegerField(verbose_name='paddingLeft')),
                ('paddingRight', models.IntegerField(verbose_name='paddingRight')),
            ],
            options={
                'verbose_name': 'Icon\u5e03\u5c40',
                'verbose_name_plural': 'Icon\u5e03\u5c40',
            },
        ),
        migrations.CreateModel(
            name='IconSwitchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=255, verbose_name='\u7248\u672c\u53f7')),
                ('game_id', models.PositiveIntegerField(verbose_name='gameId')),
                ('name', models.CharField(max_length=255, verbose_name='\u6e38\u620f\u540d\u79f0')),
                ('socket_url', models.PositiveIntegerField(choices=[(0, b'\xe5\xaf\x8c\xe8\xb1\xaa\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (1, b'\xe4\xb8\x89\xe6\xb6\x88\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8')], verbose_name='\u670d\u52a1\u5668')),
                ('switch', models.PositiveIntegerField(default=1, verbose_name='switch')),
                ('framesInterval', models.PositiveIntegerField(default=10000, verbose_name='\u64ad\u653e\u901f\u5ea6')),
            ],
            options={
                'verbose_name': 'Icon\u5207\u6362',
                'verbose_name_plural': 'Icon\u5207\u6362',
            },
        ),
        migrations.CreateModel(
            name='LabelSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(verbose_name='\u9ad8\u5ea6')),
                ('scale', models.FloatField(verbose_name='\u7f29\u653e\u6bd4\u4f8b')),
                ('yfromtop', models.PositiveIntegerField(verbose_name='\u56fe\u7247\u4e2d\u5fc3\u70b9\u79bb\u4e0a\u65b9\u8ddd\u79bb')),
                ('imgurl', models.CharField(max_length=512, verbose_name='\u6807\u9898ICON')),
            ],
            options={
                'verbose_name': '\u6807\u9898',
                'verbose_name_plural': '\u6807\u9898',
            },
        ),
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.IntegerField(verbose_name='id')),
                ('type', models.IntegerField(verbose_name='type')),
                ('x', models.IntegerField(verbose_name='x')),
                ('y', models.IntegerField(verbose_name='y')),
                ('foreignkey_iconswitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oriented.IconSwitchModel', verbose_name='Icon\u5207\u6362')),
            ],
            options={
                'verbose_name': '\u4f4d\u7f6e\u8bbe\u5b9a',
                'verbose_name_plural': '\u4f4d\u7f6e\u8bbe\u5b9a',
            },
        ),
        migrations.CreateModel(
            name='PullSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.FloatField(verbose_name='\u7f29\u653e\u6bd4\u4f8b')),
                ('positionX', models.FloatField(verbose_name='positionX')),
                ('positionY', models.FloatField(verbose_name='positionY')),
                ('imgurl0', models.CharField(max_length=512, verbose_name='\u672a\u62c9\u53d6\u65f6\u56fe')),
                ('imgurl1', models.CharField(max_length=512, verbose_name='\u62c9\u53d6\u65f6\u56fe')),
                ('isredon', models.BooleanField(default=1, verbose_name='\u663e\u793a\u7ea2\u70b9')),
            ],
            options={
                'verbose_name': '\u62c9\u6309\u94ae',
                'verbose_name_plural': '\u62c9\u6309\u94ae',
            },
        ),
        migrations.CreateModel(
            name='SlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=255, verbose_name='\u7248\u672c\u53f7')),
                ('game_id', models.PositiveIntegerField(verbose_name='gameId')),
                ('name', models.CharField(max_length=255, verbose_name='\u6e38\u620f\u540d\u79f0')),
                ('socket_url', models.PositiveIntegerField(choices=[(0, b'\xe5\xaf\x8c\xe8\xb1\xaa\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (1, b'\xe4\xb8\x89\xe6\xb6\x88\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8')], verbose_name='\u670d\u52a1\u5668')),
                ('switch', models.PositiveIntegerField(default=1, verbose_name='switch')),
                ('fromWhere', models.PositiveIntegerField(default=0, verbose_name='\u5c55\u5f00\u65b9\u5411')),
                ('reddot', models.CharField(default='https://sanxqn.nalrer.cn/tysanxiao/test/LikeConfigRes/reddot.png', max_length=512, verbose_name='\u89d2\u6807')),
                ('mask', models.CharField(default='https://sanxqn.nalrer.cn/tysanxiao/test/LikeConfigRes/adRes.png', max_length=512, verbose_name='\u8499\u5c42')),
                ('viewAdCounts', models.PositiveIntegerField(default=3, verbose_name='viewAdCounts')),
            ],
            options={
                'verbose_name': '\u4fa7\u62c9\u6846',
                'verbose_name_plural': '\u4fa7\u62c9\u6846',
            },
        ),
        migrations.CreateModel(
            name='StripModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=255, verbose_name='\u7248\u672c\u53f7')),
                ('game_id', models.PositiveIntegerField(verbose_name='gameId')),
                ('name', models.CharField(max_length=255, verbose_name='\u6e38\u620f\u540d\u79f0')),
                ('socket_url', models.PositiveIntegerField(choices=[(0, b'\xe5\xaf\x8c\xe8\xb1\xaa\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (1, b'\xe4\xb8\x89\xe6\xb6\x88\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8')], verbose_name='\u670d\u52a1\u5668')),
                ('label', models.CharField(max_length=512, verbose_name='\u6807\u9898')),
                ('bg', models.CharField(max_length=512, verbose_name='\u80cc\u666f\u56fe')),
                ('reddot', models.CharField(max_length=512, verbose_name='\u89d2\u6807')),
                ('spacingX', models.PositiveIntegerField(verbose_name='\u95f4\u8ddd')),
                ('iconWidth', models.PositiveIntegerField(verbose_name='\u5bbd\u5ea6')),
                ('iconHeight', models.PositiveIntegerField(verbose_name='\u9ad8\u5ea6')),
                ('switch', models.PositiveIntegerField(default=1, verbose_name='switch')),
                ('viewAdCounts', models.PositiveIntegerField(default=5, verbose_name='viewAdCounts')),
                ('framesInterval', models.PositiveIntegerField(default=50, verbose_name='\u64ad\u653e\u901f\u5ea6')),
            ],
            options={
                'verbose_name': '\u5bfc\u6d41\u6761',
                'verbose_name_plural': '\u5bfc\u6d41\u6761',
            },
        ),
        migrations.CreateModel(
            name='TextSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='size')),
                ('yfromIcon', models.PositiveIntegerField(verbose_name='yfromIcon')),
                ('colorR', models.PositiveIntegerField(verbose_name='colorR')),
                ('colorG', models.PositiveIntegerField(verbose_name='colorG')),
                ('colorB', models.PositiveIntegerField(verbose_name='colorB')),
                ('foreignkey_labelSlideOver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846')),
            ],
            options={
                'verbose_name': '\u6587\u672c',
                'verbose_name_plural': '\u6587\u672c',
            },
        ),
        migrations.AddField(
            model_name='pullslideovermodel',
            name='foreignkey_labelSlideOver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846'),
        ),
        migrations.AddField(
            model_name='labelslideovermodel',
            name='foreignkey_labelSlideOver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846'),
        ),
        migrations.AddField(
            model_name='gridslideovermodel',
            name='foreignkey_labelSlideOver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846'),
        ),
        migrations.AddField(
            model_name='gamestripmodel',
            name='foreignkey_strip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oriented.StripModel', verbose_name='\u5bfc\u6d41\u6761'),
        ),
        migrations.AddField(
            model_name='gameslideovermodel',
            name='foreignkey_labelSlideOver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846'),
        ),
        migrations.AddField(
            model_name='gameiconswitchmodel',
            name='foreignkey_iconswitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oriented.IconSwitchModel', verbose_name='Icon\u5207\u6362'),
        ),
        migrations.AddField(
            model_name='bgslideovermodel',
            name='foreignkey_labelSlideOver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846'),
        ),
    ]
