# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameIconSwitchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='\u8f93\u5165\u6570\u5b57', verbose_name='\u5e8f\u53f7')),
                ('wxAppId', models.CharField(choices=[(b'wxaa5c62c26ee49681', b'\xe7\x96\xaf\xe7\x8b\x82\xe6\x9e\xaa\xe6\x89\x8b'), (b'wx57f49f44206958e6', b'\xe6\xac\xa2\xe4\xb9\x90\xe9\x92\x93\xe9\xb1\xbc\xe5\xa4\xa7\xe5\xb8\x88'), (b'wxde9361a6865997fc', b'3D\xe7\x90\x83\xe7\x90\x83\xe6\x89\x93\xe7\xa0\x96\xe5\x9d\x97')], max_length=20, verbose_name='wxAppId')),
                ('weight', models.PositiveIntegerField(verbose_name='\u6743\u91cd')),
                ('scale', models.FloatField(verbose_name='\u7f29\u653e\u6bd4\u4f8b')),
                ('imgLink', models.CharField(max_length=512, verbose_name='ICON')),
                ('openType', models.BooleanField(default=1, verbose_name='\u6253\u5f00\u65b9\u5f0f')),
                ('clickHide', models.BooleanField(verbose_name='\u662f\u5426\u9690\u85cf')),
                ('topath', models.CharField(max_length=256, verbose_name='topath')),
                ('bi_iconId', models.CharField(max_length=10, verbose_name='bI_IconId')),
                ('bi_landing_page', models.CharField(max_length=255, verbose_name='bI_\u843d\u5730\u9875')),
                ('bi_landing_page_id', models.CharField(max_length=10, verbose_name='bI_\u843d\u5730\u9875Id')),
                ('bi_educe_game', models.CharField(max_length=10, verbose_name='bI_\u5185\u90e8path')),
            ],
            options={
                'verbose_name': '\u5bfc\u51fa\u6e38\u620f',
                'verbose_name_plural': '\u5bfc\u51fa\u6e38\u620f',
            },
        ),
        migrations.CreateModel(
            name='GameStripModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='\u8f93\u5165\u6570\u5b57', verbose_name='\u5e8f\u53f7')),
                ('wxAppId', models.CharField(choices=[(b'wxaa5c62c26ee49681', b'\xe7\x96\xaf\xe7\x8b\x82\xe6\x9e\xaa\xe6\x89\x8b'), (b'wx57f49f44206958e6', b'\xe6\xac\xa2\xe4\xb9\x90\xe9\x92\x93\xe9\xb1\xbc\xe5\xa4\xa7\xe5\xb8\x88'), (b'wxde9361a6865997fc', b'3D\xe7\x90\x83\xe7\x90\x83\xe6\x89\x93\xe7\xa0\x96\xe5\x9d\x97')], max_length=20, verbose_name='wxAppId')),
                ('imgLink', models.CharField(max_length=512, verbose_name='ICON')),
                ('topath', models.CharField(max_length=256, verbose_name='topath')),
                ('isClickHide', models.BooleanField(verbose_name='\u662f\u5426\u9690\u85cf')),
                ('bi_iconId', models.CharField(max_length=10, verbose_name='bI_IconId')),
                ('bi_landing_page', models.CharField(max_length=255, verbose_name='bI_\u843d\u5730\u9875')),
                ('bi_landing_page_id', models.CharField(max_length=10, verbose_name='bI_\u843d\u5730\u9875Id')),
                ('bi_educe_game', models.CharField(max_length=10, verbose_name='bI_\u5185\u90e8path')),
            ],
            options={
                'verbose_name': '\u5bfc\u51fa\u6e38\u620f',
                'verbose_name_plural': '\u5bfc\u51fa\u6e38\u620f',
            },
        ),
        migrations.CreateModel(
            name='IconSwitchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.PositiveIntegerField(unique=True, verbose_name='gameId')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u6e38\u620f\u540d\u79f0')),
                ('socket_url', models.PositiveIntegerField(choices=[(0, b'\xe5\xaf\x8c\xe8\xb1\xaa\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (1, b'\xe4\xb8\x89\xe6\xb6\x88\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8')], verbose_name='\u670d\u52a1\u5668')),
                ('switch', models.PositiveIntegerField(default=1, verbose_name='switch')),
                ('framesInterval', models.PositiveIntegerField(default=10000, verbose_name='\u64ad\u653e\u901f\u5ea6')),
            ],
            options={
                'verbose_name': 'Icon\u5207\u6362',
                'verbose_name_plural': 'Icon\u5207\u6362',
            },
        ),
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.IntegerField(verbose_name='id')),
                ('type', models.IntegerField(verbose_name='type')),
                ('x', models.IntegerField(verbose_name='x')),
                ('y', models.IntegerField(verbose_name='y')),
                ('foreignkey_iconswitch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oriented.IconSwitchModel', verbose_name='Icon\u5207\u6362')),
            ],
            options={
                'verbose_name': '\u4f4d\u7f6e\u8bbe\u5b9a',
                'verbose_name_plural': '\u4f4d\u7f6e\u8bbe\u5b9a',
            },
        ),
        migrations.CreateModel(
            name='StripModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.PositiveIntegerField(unique=True, verbose_name='gameId')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u6e38\u620f\u540d\u79f0')),
                ('socket_url', models.PositiveIntegerField(choices=[(0, b'\xe5\xaf\x8c\xe8\xb1\xaa\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (1, b'\xe4\xb8\x89\xe6\xb6\x88\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8')], verbose_name='\u670d\u52a1\u5668')),
                ('label', models.CharField(max_length=255, verbose_name='\u6807\u9898')),
                ('bg', models.CharField(max_length=255, verbose_name='\u80cc\u666f\u56fe')),
                ('reddot', models.CharField(max_length=255, verbose_name='\u89d2\u6807')),
                ('spacingX', models.PositiveIntegerField(verbose_name='\u95f4\u8ddd')),
                ('iconWidth', models.PositiveIntegerField(verbose_name='\u5bbd\u5ea6')),
                ('iconHeight', models.PositiveIntegerField(verbose_name='\u9ad8\u5ea6')),
                ('switch', models.PositiveIntegerField(default=1, verbose_name='switch')),
                ('viewAdCounts', models.PositiveIntegerField(default=5, verbose_name='viewAdCounts')),
                ('framesInterval', models.PositiveIntegerField(default=50, verbose_name='\u64ad\u653e\u901f\u5ea6')),
            ],
            options={
                'verbose_name': '\u5bfc\u6d41\u6761',
                'verbose_name_plural': '\u5bfc\u6d41\u6761',
            },
        ),
        migrations.AddField(
            model_name='gamestripmodel',
            name='foreignkey_strip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oriented.StripModel', verbose_name='\u5bfc\u6d41\u6761'),
        ),
        migrations.AddField(
            model_name='gameiconswitchmodel',
            name='foreignkey_iconswitch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oriented.IconSwitchModel', verbose_name='Icon\u5207\u6362'),
        ),
    ]
