# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oriented', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripmodel',
            name='version',
            field=models.CharField(default=uuid.UUID('5305f345-40d3-11e9-a77d-f018986427a7'), max_length=255, verbose_name='\u7248\u672c\u53f7'),
        ),
    ]
