# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-27 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oriented', '0002_remove_gameiconswitchmodel_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionY', models.FloatField(verbose_name='positionY_\u6846\u4e2d\u5fc3\u70b9\u5360\u6574\u4e2a\u5c4f\u5e55\u7684\u6bd4\u4f8b')),
                ('bottomBlkHeight', models.PositiveIntegerField(verbose_name='\u6846\u5185\u7684\u4e0b\u65b9\u7a7a\u767d\u7684\u9ad8')),
                ('imgurl', models.CharField(max_length=512, verbose_name='\u6846\u7684\u80cc\u666f\u56fe')),
            ],
            options={
                'verbose_name': '\u6846',
                'verbose_name_plural': '\u6846',
            },
        ),
        migrations.CreateModel(
            name='GameSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='\u8f93\u5165\u6570\u5b57', verbose_name='\u5e8f\u53f7')),
                ('text', models.CharField(max_length=512, verbose_name='text')),
                ('type', models.BooleanField(default=0, verbose_name='\u52a8\u56feicon')),
                ('imgLink', models.CharField(max_length=512, verbose_name='ICON')),
                ('openType', models.BooleanField(default=1, verbose_name='\u6253\u5f00\u65b9\u5f0f')),
                ('openUrl', models.CharField(choices=[(b'wxaa5c62c26ee49681', b'\xe7\x96\xaf\xe7\x8b\x82\xe6\x9e\xaa\xe6\x89\x8b'), (b'wx57f49f44206958e6', b'\xe6\xac\xa2\xe4\xb9\x90\xe9\x92\x93\xe9\xb1\xbc\xe5\xa4\xa7\xe5\xb8\x88'), (b'wxde9361a6865997fc', b'3D\xe7\x90\x83\xe7\x90\x83\xe6\x89\x93\xe7\xa0\x96\xe5\x9d\x97')], max_length=20, verbose_name='wxAppId')),
                ('isredon', models.BooleanField(default=1, verbose_name='\u663e\u793a\u7ea2\u70b9')),
                ('topath', models.CharField(max_length=512, verbose_name='topath')),
                ('bi_iconId', models.CharField(max_length=10, verbose_name='bI_IconId')),
                ('bi_landing_page', models.CharField(max_length=512, verbose_name='bI_\u843d\u5730\u9875')),
                ('bi_landing_page_id', models.CharField(max_length=10, verbose_name='bI_\u843d\u5730\u9875Id')),
                ('bi_educe_game', models.CharField(max_length=10, verbose_name='bI_\u5185\u90e8path')),
            ],
            options={
                'verbose_name': '\u5bfc\u51fa\u6e38\u620f',
                'verbose_name_plural': '\u5bfc\u51fa\u6e38\u620f',
            },
        ),
        migrations.CreateModel(
            name='GridSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconsWidth', models.IntegerField(verbose_name='iconsWidth')),
                ('iconsHeight', models.IntegerField(verbose_name='iconsHeight')),
                ('spacingX', models.IntegerField(verbose_name='spacingX')),
                ('spacingY', models.IntegerField(verbose_name='spacingY')),
                ('paddingLeft', models.IntegerField(verbose_name='paddingLeft')),
                ('paddingRight', models.IntegerField(verbose_name='paddingRight')),
            ],
            options={
                'verbose_name': 'Icon\u5e03\u5c40',
                'verbose_name_plural': 'Icon\u5e03\u5c40',
            },
        ),
        migrations.CreateModel(
            name='LabelSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(verbose_name='\u9ad8\u5ea6')),
                ('scale', models.FloatField(verbose_name='\u7f29\u653e\u6bd4\u4f8b')),
                ('yfromtop', models.PositiveIntegerField(verbose_name='\u56fe\u7247\u4e2d\u5fc3\u70b9\u79bb\u4e0a\u65b9\u8ddd\u79bb')),
                ('imgurl', models.CharField(max_length=512, verbose_name='\u6807\u9898ICON')),
            ],
            options={
                'verbose_name': '\u6807\u9898',
                'verbose_name_plural': '\u6807\u9898',
            },
        ),
        migrations.CreateModel(
            name='PullSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.FloatField(verbose_name='\u7f29\u653e\u6bd4\u4f8b')),
                ('positionX', models.FloatField(verbose_name='positionX')),
                ('positionY', models.FloatField(verbose_name='positionY')),
                ('imgurl0', models.CharField(max_length=512, verbose_name='\u672a\u62c9\u53d6\u65f6\u56fe')),
                ('imgurl1', models.CharField(max_length=512, verbose_name='\u62c9\u53d6\u65f6\u56fe')),
                ('isredon', models.BooleanField(default=1, verbose_name='\u663e\u793a\u7ea2\u70b9')),
            ],
            options={
                'verbose_name': '\u62c9\u6309\u94ae',
                'verbose_name_plural': '\u62c9\u6309\u94ae',
            },
        ),
        migrations.CreateModel(
            name='SlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.PositiveIntegerField(unique=True, verbose_name='gameId')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u6e38\u620f\u540d\u79f0')),
                ('socket_url', models.PositiveIntegerField(choices=[(0, b'\xe5\xaf\x8c\xe8\xb1\xaa\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8'), (1, b'\xe4\xb8\x89\xe6\xb6\x88\xe6\x9c\x8d\xe5\x8a\xa1\xe5\x99\xa8')], verbose_name='\u670d\u52a1\u5668')),
                ('switch', models.PositiveIntegerField(default=1, verbose_name='switch')),
                ('fromWhere', models.PositiveIntegerField(default=0, verbose_name='\u5c55\u5f00\u65b9\u5411')),
                ('reddot', models.CharField(default='https://sanxqn.nalrer.cn/tysanxiao/test/LikeConfigRes/reddot.png', max_length=512, verbose_name='\u89d2\u6807')),
                ('mask', models.CharField(default='https://sanxqn.nalrer.cn/tysanxiao/test/LikeConfigRes/adRes.png', max_length=512, verbose_name='\u8499\u5c42')),
                ('viewAdCounts', models.PositiveIntegerField(default=3, verbose_name='viewAdCounts')),
            ],
            options={
                'verbose_name': '\u4fa7\u62c9\u6846',
                'verbose_name_plural': '\u4fa7\u62c9\u6846',
            },
        ),
        migrations.CreateModel(
            name='TextSlideOverModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(verbose_name='size')),
                ('yfromIcon', models.PositiveIntegerField(verbose_name='yfromIcon')),
                ('colorR', models.PositiveIntegerField(verbose_name='colorR')),
                ('colorG', models.PositiveIntegerField(verbose_name='colorG')),
                ('colorB', models.PositiveIntegerField(verbose_name='colorB')),
                ('foreignkey_labelSlideOver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846')),
            ],
            options={
                'verbose_name': '\u6587\u672c',
                'verbose_name_plural': '\u6587\u672c',
            },
        ),
        migrations.AlterField(
            model_name='gameiconswitchmodel',
            name='bi_landing_page',
            field=models.CharField(max_length=512, verbose_name='bI_\u843d\u5730\u9875'),
        ),
        migrations.AlterField(
            model_name='gameiconswitchmodel',
            name='topath',
            field=models.CharField(max_length=512, verbose_name='topath'),
        ),
        migrations.AlterField(
            model_name='gamestripmodel',
            name='bi_landing_page',
            field=models.CharField(max_length=512, verbose_name='bI_\u843d\u5730\u9875'),
        ),
        migrations.AlterField(
            model_name='gamestripmodel',
            name='topath',
            field=models.CharField(max_length=512, verbose_name='topath'),
        ),
        migrations.AlterField(
            model_name='stripmodel',
            name='bg',
            field=models.CharField(max_length=512, verbose_name='\u80cc\u666f\u56fe'),
        ),
        migrations.AlterField(
            model_name='stripmodel',
            name='label',
            field=models.CharField(max_length=512, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='stripmodel',
            name='reddot',
            field=models.CharField(max_length=512, verbose_name='\u89d2\u6807'),
        ),
        migrations.AddField(
            model_name='pullslideovermodel',
            name='foreignkey_labelSlideOver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846'),
        ),
        migrations.AddField(
            model_name='labelslideovermodel',
            name='foreignkey_labelSlideOver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846'),
        ),
        migrations.AddField(
            model_name='gridslideovermodel',
            name='foreignkey_labelSlideOver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846'),
        ),
        migrations.AddField(
            model_name='gameslideovermodel',
            name='foreignkey_labelSlideOver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846'),
        ),
        migrations.AddField(
            model_name='bgslideovermodel',
            name='foreignkey_labelSlideOver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oriented.SlideOverModel', verbose_name='\u4fa7\u62c9\u6846'),
        ),
    ]
