# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oriented', '0002_auto_20190307_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iconswitchmodel',
            name='version',
        ),
        migrations.RemoveField(
            model_name='slideovermodel',
            name='version',
        ),
        migrations.RemoveField(
            model_name='stripmodel',
            name='version',
        ),
    ]
