# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 20:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('oriented', '0003_auto_20190307_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='iconswitchmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slideovermodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripmodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 3, 7, 20, 40, 35, 895870), verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
