version: '3'
services:

  mysql:
    container_name: mysql5.7
    image: mysql:5.7
    volumes:
      # mkdir mysqldata first
      - ../mysql/data:/var/lib/mysql
      - ../mysql/conf:/etc/mysql/conf.d
      - ../mysql/logs:/var/log/mysql
    restart: always
    ports:
      - "3306:3306"
    command: mysqld --explicit_defaults_for_timestamp=true
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai

  gm:
    container_name: gm
    build: .
    volumes:
      - ./:/root/code
    ports:
      - "8080:9000"
    depends_on:
      - mysql