version: '3'
services:

  mysql:
    image: mysql:5.7
    user: 1000:1000
    volumes:
      # mkdir mysqldata first
      - ../mysql/data:/var/lib/mysql
      - ../mysql/conf:/etc/mysql/conf.d
      - ../mysql/logs:/var/log/mysql
    restart: always
    ports:
      - "3306:3306"
    command: mysqld
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai

  management:
    build: .
    volumes:
      - ./:/root/code
    ports:
      - "8080:9000"
    depends_on:
      - mysql