version: '1.0'
services:

  mysql:
    image: mysql:5.7
    user: 1000:1000
    volumes:
      # mkdir mysqldata first
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
    restart: always
    ports:
      - "33061:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai

  gm:
    build: .
    volumes:
      - ./:/root/code
    ports:
      - "8080:9000"
    depends_on:
      - mysql