from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', index),
    #url(r'index.html', index),
    url(r'welcome.html', welcome),

    url(r'iconConfig/list.html', OrientedIconConfig.handleList),
    url(r'iconConfig/add.html', OrientedIconConfig.handleAdd),
    url(r'iconConfig/save.html', OrientedIconConfig.handleSave),
    url(r'iconConfig/look.html', OrientedIconConfig.handleLook),
    url(r'iconConfig/update.html', OrientedIconConfig.handleUpdate),
    url(r'iconConfig/del.html', OrientedIconConfig.handleDel),
    url(r'iconConfig/delAll.html', OrientedIconConfig.handleDelAll),
    url(r'iconConfig/data.html', OrientedIconConfig.handleData),
    url(r'iconConfig/copy.html', OrientedIconConfig.handleCopy),

    url(r'iconConfig/sub/list.html', OrientedIconSub.handleList),
    url(r'iconConfig/sub/add.html', OrientedIconSub.handleAdd),
    url(r'iconConfig/sub/save.html', OrientedIconSub.handleSave),
    url(r'iconConfig/sub/look.html', OrientedIconSub.handleLook),
    url(r'iconConfig/sub/update.html', OrientedIconSub.handleUpdate),
    url(r'iconConfig/sub/data.html', OrientedIconSub.handleData),
    url(r'iconConfig/sub/del.html', OrientedIconSub.handleDel),
    url(r'iconConfig/sub/delAll.html', OrientedIconSub.handleDelAll),
    url(r'iconConfig/sub/copy.html', OrientedIconSub.handleCopy),

    url(r'iconConfig/position/list.html', OrientedIconPosition.handleList),
    url(r'iconConfig/position/add.html', OrientedIconPosition.handleAdd),
    url(r'iconConfig/position/save.html', OrientedIconPosition.handleSave),
    url(r'iconConfig/position/look.html', OrientedIconPosition.handleLook),
    url(r'iconConfig/position/update.html', OrientedIconPosition.handleUpdate),
    url(r'iconConfig/position/data.html', OrientedIconPosition.handleData),
    url(r'iconConfig/position/del.html', OrientedIconPosition.handleDel),
    url(r'iconConfig/position/delAll.html', OrientedIconPosition.handleDelAll),
    url(r'iconConfig/position/copy.html', OrientedIconPosition.handleCopy),

    url(r'stripConfig/list.html', StripConfig.handleList),
    url(r'stripConfig/add.html', StripConfig.handleAdd),
    url(r'stripConfig/save.html', StripConfig.handleSave),
    url(r'stripConfig/look.html', StripConfig.handleLook),
    url(r'stripConfig/update.html', StripConfig.handleUpdate),
    url(r'stripConfig/data.html', StripConfig.handleData),
    url(r'stripConfig/del.html', StripConfig.handleDel),
    url(r'stripConfig/delAll.html', StripConfig.handleDelAll),
    url(r'stripConfig/copy.html', StripConfig.handleCopy),

    url(r'stripConfig/sub/list.html', StripSub.handleList),
    url(r'stripConfig/sub/add.html', StripSub.handleAdd),
    url(r'stripConfig/sub/save.html', StripSub.handleSave),
    url(r'stripConfig/sub/look.html', StripSub.handleLook),
    url(r'stripConfig/sub/update.html', StripSub.handleUpdate),
    url(r'stripConfig/sub/data.html', StripSub.handleData),
    url(r'stripConfig/sub/del.html', StripSub.handleDel),
    url(r'stripConfig/sub/delAll.html', StripSub.handleDelAll),
    url(r'stripConfig/sub/copy.html', StripSub.handleCopy),

    url(r'slideoverConfig/list.html', SlideoverConfig.handleList),
    url(r'slideoverConfig/add.html', SlideoverConfig.handleAdd),
    url(r'slideoverConfig/save.html', SlideoverConfig.handleSave),
    url(r'slideoverConfig/look.html', SlideoverConfig.handleLook),
    url(r'slideoverConfig/update.html', SlideoverConfig.handleUpdate),
    url(r'slideoverConfig/data.html', SlideoverConfig.handleData),
    url(r'slideoverConfig/del.html', SlideoverConfig.handleDel),
    url(r'slideoverConfig/delAll.html', SlideoverConfig.handleDelAll),
    url(r'slideoverConfig/copy.html', SlideoverConfig.handleCopy),

    url(r'slideoverConfig/sub/list.html', SlideoverSub.handleList),
    url(r'slideoverConfig/sub/add.html', SlideoverSub.handleAdd),
    url(r'slideoverConfig/sub/save.html', SlideoverSub.handleSave),
    url(r'slideoverConfig/sub/look.html', SlideoverSub.handleLook),
    url(r'slideoverConfig/sub/update.html', SlideoverSub.handleUpdate),
    url(r'slideoverConfig/sub/data.html', SlideoverSub.handleData),
    url(r'slideoverConfig/sub/del.html', SlideoverSub.handleDel),
    url(r'slideoverConfig/sub/delAll.html', SlideoverSub.handleDelAll),
    url(r'slideoverConfig/sub/copy.html', SlideoverSub.handleCopy),

    url(r'slideoverConfig/bg/look.html', SlideoverConfig.handleBgLook),
    url(r'slideoverConfig/bg/update.html', SlideoverConfig.handleBgUpdate),


    url(r'push/list.html', PushView.handleList),
    url(r'push/data.html', PushView.handleData),
    url(r'push/look.html', PushView.handleLook),
    url(r'push/look_online.html', PushView.handleLookOnline),
    url(r'push/push_online.html', PushView.handlePushOnline),
]